# Generated by Django 5.0.1 on 2024-01-19 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Course Name')),
                ('description', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('is_active', models.BooleanField(default=True, verbose_name='Avilable')),
                ('image', models.ImageField(upload_to='image')),
            ],
        ),
    ]
