# Generated by Django 5.0.1 on 2024-01-19 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coapp', '0002_course_cate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.CharField(max_length=100),
        ),
    ]
