# Generated by Django 5.0.1 on 2024-01-19 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coapp', '0003_alter_course_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
